### ISSUE TITLE
Data sources

### ISSUE THREAD

**Issue by JonoSax** [jonathandunn/corpus_analysis#1]
Hi, 

Just wondering where the data sources are for the .gz files used for the pandas tables (ie economic.congress.1931-2016)? 

I have cloned the repo locally but the data is not included in the repo and there is no link to download the data. Would be great to be able to run the notebooks locally. 

Cheers

**Comment by jonathandunn** [comment]
The data isn't a part of this particular repo, but much of it should be available here: https://doi.org/10.24433/CO.3402613.v1
